// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package health_route

import (
	"github.com/evanhongo/happy-golang/api"
)

// Injectors from wire.go:

func CreateRouter() (api.IRouter, error) {
	iSchema := NewPingRequestSchema()
	pingHandler := NewPingHandler(iSchema)
	iRouter := NewHealthRouter(pingHandler)
	return iRouter, nil
}
