// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package job_route

import (
	"github.com/evanhongo/happy-golang/api"
	"github.com/evanhongo/happy-golang/pkg/job_queue"
	"github.com/evanhongo/happy-golang/service/job"
)

// Injectors from wire.go:

func CreateRouter() (api.IRouter, error) {
	iJobService := service.NewJobService()
	iJobQueue, err := job_queue.NewJobQueue(iJobService)
	if err != nil {
		return nil, err
	}
	jobHandler := NewJobHandler(iJobQueue)
	iRouter := NewJobRouter(jobHandler)
	return iRouter, nil
}
