// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/evanhongo/happy-golang/api"
	"github.com/evanhongo/happy-golang/api/route/auth"
	"github.com/evanhongo/happy-golang/api/route/job"
	"github.com/evanhongo/happy-golang/pkg/job_queue"
	service2 "github.com/evanhongo/happy-golang/service/auth"
	"github.com/evanhongo/happy-golang/service/job"
)

// Injectors from wire.go:

func CreateCmd() (*Cmd, error) {
	iJobService := service.NewJobService()
	iJobQueue, err := job_queue.NewJobQueue(iJobService)
	if err != nil {
		return nil, err
	}
	jobHandler := job.NewJobHandler(iJobQueue)
	iAuthService := service2.NewAuthService()
	authHandler := auth.NewAuthHandler(iAuthService)
	server := api.NewHttpServer(jobHandler, authHandler)
	cmd := NewCmd(server, iJobQueue)
	return cmd, nil
}
