// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package docs_route

import (
	"github.com/evanhongo/happy-golang/api"
)

// Injectors from wire.go:

func CreateRouter() (api.IRouter, error) {
	iRouter := NewDocsRouter()
	return iRouter, nil
}
